#!/bin/bash -e
# install script for Fuettr Server and Java-Application

THISUSER=/home/$USER

echo "
--> downloading and installing node.js..."
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install -y nodejs

echo "
--> downloading and installing git..."
sudo apt install -y git

echo "
--> setting git credentials..."
git config --global user.name "fuettr"
git config --global user.email "fuettr@gmail.com"

echo "
--> downloading..."
cd $THISUSER && mkdir git
cd $THISUSER/git && git clone https://github.com/Katzenfuetterungsanlage/fuettr_prototype.git
cd $THISUSER/git/fuettr_prototype && git pull

echo "
--> copying rc.local..."
sudo rsync -aP $THISUSER/git/fuettr_prototype/rc.local /etc/rc.local

echo "
--> edititng rc.local..."
sudo sed -i 's/USER/$THISUSER/g' /etc/rc.local

echo "
--> installing node dependencies..."
sudo npm i -g npm
sudo npm i -g @angular/cli gulp npm-install-missing
cd $THISUSER/git/fuettr_prototype/Web_Application/Webserver/ng2 && sudo npm i --unsafe-perm
cd $THISUSER/git/fuettr_prototype/Web_Application/Webserver/server && npm i

echo "
--> building server..."
cd $THISUSER/git/fuettr_prototype/Web_Application/Webserver/ng2 && sudo ng build
cd $THISUSER/git/fuettr_prototype/Web_Application/Webserver/server && sudo gulp cleanAndBuild

echo "
--> starting server..."
cd $THISUSER/git/fuettr_prototype/Web_Application/Webserver/server/dist && sudo node main.js &

echo "
done"