#!/bin/bash -e
# Testscript

echo -e "\e[92m
--> getting serialnumber...\e[0m"
IFACE=$(ip route show default | awk '/default/ {print $5}' )
read $MAC </sys/class/net/$IFACE/address

curl -X POST \
-H "Content-type: application/json" \
-d '{"mac":"$MAC"}' \
'100.0.0.1:2525/serialnumber'