#!/bin/bash -e
# install script for Fuettr Server and Java-Application

THISUSER=/home/$USER

echo "$THISUSER"

echo "
downloading..."
cd $THISUSER/git/fuettr_prototype && git pull

echo "
creating rc.local..."
echo "#!/bin/sh -e
#
# rc.local

sudo service cron start &

cd $THISUSER/git/fuettr_prototype/Web_Application/Webserver/ng2 && npm start &

exit 0" | sudo tee /etc/rc.local

echo "rebooting..."
# sudo reboot